### PR TITLE
Taa b213 259

### PR DESCRIPTION
**Pull request by ozgurSeker80**
this is latest changes on the ozgur class regarding the last update this ticket

### CODE REVIEW

**Comment by danyalwalker** [comment]
Nice code

**Review by alcevik — APPROVED** [review]
gut

**Comment by danyalwalker** [comment]
Nice code

**Review by abbi-code — APPROVED** [review]

**Review by Emin-86 — COMMENTED** [review]
good job

**Comment by abbi-code** [comment]
all good ready to merge

**Comment by danyalwalker** [comment]
Nice code

**Pull request merged**
